# Uncomment this line to define a global platform for your project
platform :ios, '10.3'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SpinWheelExample' do
    pod 'SpinWheelControl'
end

